#!/usr/local/bin/lua

---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by korisd.
--- DateTime: 6/1/18 9:08 AM
---

local data = dofile( arg[1] )
local csv = {}
local header = "x,y,z"
table.insert( csv, header )
for _, i in ipairs( data ) do
    local line = i.x .. "," .. i.y .. ","  .. "," .. i.z
    table.insert( csv, line )
end

file = io.open( arg[2] .. ".csv", "w+" )

for _,i in ipairs( csv ) do
    file:write( i .."\n" )
end

file:close()