#!/usr/local/bin/lua

---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by korisd.
--- DateTime: 6/1/18 12:57 PM
---

local working_directory = arg[1]
local kinematic_model = arg[2]

local coord_file = arg[1] .. "/coodidinates.lua"
local lim_file = arg[1] .. "/lim_file.lua"
local res_file = arg[1] .. "result"

assert( loadfile( "generation.lua" )( lim_file, coord_file ) )
assert( loadfile( kinematic_model )( coord_file, res_file ) )
assert( loadfile( "excel.lua" )( res_file .. "_valid.lua", "graph" ) )