---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by korisd.
--- DateTime: 6/1/18 12:08 AM
---

local v = {}

function v.validate( t )
    local valid = true
    for _,i in ipairs( t ) do
        if( i ~= i ) then
            valid = false
            break
        end
    end
    return valid
end

return v